# Generated by Django 5.2.3 on 2025-06-17 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_remove_course_owner_remove_lesson_owner"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pay_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="дата оплаты"),
                ),
                ("payment_amount", models.IntegerField(verbose_name="сумма оплаты")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("наличные", "Наличные"),
                            ("перевод на счет", "Перевод на счет"),
                        ],
                        default="наличные",
                        max_length=15,
                    ),
                ),
                (
                    "pay_course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите пользователя",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materials.course",
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "pay_lesson",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите пользователя",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materials.lesson",
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите пользователя",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
