# Generated by Django 5.2.3 on 2025-10-26 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_course_owner_lesson_owner"),
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="pay_course",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите курс",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="materials.course",
                verbose_name="Оплата курса",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="pay_lesson",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите урок",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="materials.lesson",
                verbose_name="Оплата урока",
            ),
        ),
    ]
