# Generated by Django 5.2.3 on 2025-11-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_payments_options_payments_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_method",
            field=models.CharField(
                choices=[("наличные", "Наличные"), ("card", "card")],
                default="card",
                max_length=15,
            ),
        ),
    ]
