# Generated by Django 5.2.3 on 2025-11-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_payments_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="pay_date",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="дата оплаты"
            ),
        ),
    ]
