# Generated by Django 5.2.3 on 2025-06-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_alter_lesson_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Ссылка на видео"
            ),
        ),
    ]
