# Generated by Django 5.2.3 on 2025-06-17 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_alter_lesson_video_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="owner",
        ),
    ]
