# Generated by Django 5.2.3 on 2025-10-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="video_url",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Ссылка на видео"
            ),
        ),
    ]
