# Generated by Django 5.2.3 on 2025-11-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0007_course_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Цена курса"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="stripe_product_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ID продукта Stripe"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Цена урока"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="stripe_product_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ID продукта Stripe"
            ),
        ),
    ]
